version: '3'
services:

  db:
    image: mongo:7.0.0
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  rabbit:
    image: rabbitmq:3.12.4-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile-dev
    container_name: video-streaming
    volumes:
      - /tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z
      - ./video-streaming/videos:/usr/src/app/videos:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=development
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
    depends_on:
      - rabbit
    restart: "no"

